# 1.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

## Часть 1 (19 баллов)

1) Импортировать numpy и написать версию (1 балл)

In [1]:
import numpy as np

In [2]:
np.version.version

'1.17.2'

2) Создать нулевой вектор размера 10 (1 балл)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7 (2 балла)


In [4]:
np.full(7, 7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100 включительно (2 балла)

In [5]:
arr = np.arange(10, 101)
arr[arr % 2 == 0]

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд (4 балла)

In [6]:
arr = np.random.random_sample(10)
arr[::-1]

array([0.75729695, 0.89901646, 0.01843131, 0.95845722, 0.056151  ,
       0.89371001, 0.85247141, 0.74040843, 0.27122517, 0.83983848])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9 (4 балла)

In [7]:
arr = np.arange(9)
arr.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх. (5 баллов)

In [8]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

## Часть 2 (26 баллов)

1) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки. (2 балла)

In [9]:
np.diag([1,2,3,4]) - np.eye(4) * 7 + np.full((4,4),7)

array([[1., 7., 7., 7.],
       [7., 2., 7., 7.],
       [7., 7., 3., 7.],
       [7., 7., 7., 4.]])

2) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках. (2 балла)

In [10]:
a = np.array([1,2,3,4]).reshape(1,4)
b = np.ones((4,1))
a * b


array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

3) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки (3 балла)

In [11]:
arr = np.random.random_sample((10,10))
arr - np.mean(arr, axis = 1) * np.ones((10, 1))

array([[ 0.28888125, -0.32941081, -0.17803315,  0.32577944, -0.05866846,
         0.29623279, -0.42455384, -0.21110213,  0.61301219, -0.51683528],
       [-0.42938576,  0.20511318, -0.15774566, -0.32471585, -0.07377826,
         0.05568232, -0.37564749, -0.25353091, -0.12026129,  0.30553992],
       [-0.30956034,  0.54665494, -0.35607443,  0.02431253, -0.12839725,
         0.40068314,  0.23512448, -0.21108597,  0.40598893, -0.33147483],
       [-0.46267252, -0.01165859, -0.47771464,  0.1223298 , -0.01163588,
         0.26543027,  0.37697559,  0.06324502,  0.48277774, -0.03850018],
       [ 0.10382113,  0.43985337, -0.43931718, -0.48881313,  0.25545711,
        -0.1989023 , -0.40912553, -0.34508173,  0.56885962,  0.11577372],
       [ 0.03336036,  0.1432684 ,  0.26723515,  0.16097362,  0.10845906,
        -0.32026028, -0.51485209,  0.38847013,  0.44641735,  0.22759023],
       [-0.18719789,  0.4101189 , -0.32968334,  0.22371357, -0.0362923 ,
         0.19985346,  0.14962188,  0.22148049

4) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца (4 балла)

In [12]:
arr = np.random.random_sample((10,10))
arr - np.ones((1,10)) * np.median(arr, axis = 0).T

array([[ 0.39440697, -0.15679602, -0.29350232,  0.21301616, -0.18111844,
        -0.07420957, -0.06337966,  0.39968016, -0.11269275, -0.19200836],
       [-0.15985181,  0.27258167,  0.50804791,  0.26947781, -0.48875515,
        -0.21322515, -0.10059203, -0.37674491,  0.01468875,  0.52083728],
       [ 0.14873239,  0.25570821,  0.34427131,  0.27158193,  0.35043324,
         0.45172648, -0.06838046, -0.0993713 ,  0.21580366,  0.27330141],
       [ 0.56244628,  0.05537324, -0.19725317,  0.02148729,  0.18641176,
         0.38755685, -0.05864363,  0.3798238 , -0.01180182,  0.16709025],
       [-0.13610835, -0.25577489, -0.16004891, -0.02148729, -0.2164681 ,
         0.1541475 ,  0.26404073,  0.08913181,  0.01180182, -0.12896399],
       [-0.37852467, -0.37428565, -0.16039026,  0.29132096, -0.41604612,
         0.07420957, -0.04797725,  0.26292218, -0.56263576, -0.05287773],
       [-0.05436528, -0.05537324,  0.40783737, -0.33437365,  0.17983946,
        -0.27684582,  0.04797725, -0.08913181

5) Создать матрицу случайных чисел 5x5. Добавить к ней столбцы максимумов и минимумов по строкам. Получится матрица 5x7. (4 балла) 

In [28]:
arr = np.random.random_sample((5,5))
arr1 = np.amax(a=arr,axis=1).reshape((5,1))
arr2 = np.amin(a=arr,axis=1).reshape((5,1))
np.hstack((arr,arr1,arr2))

array([[0.81671364, 0.29440323, 0.39009755, 0.79736925, 0.59270666,
        0.81671364, 0.29440323],
       [0.61386361, 0.03016157, 0.22865326, 0.58098902, 0.49847818,
        0.61386361, 0.03016157],
       [0.15804597, 0.56792969, 0.02000813, 0.46200122, 0.89214281,
        0.89214281, 0.02000813],
       [0.42134181, 0.46954445, 0.63526811, 0.11757921, 0.47359806,
        0.63526811, 0.11757921],
       [0.03802867, 0.14864713, 0.07896533, 0.86578692, 0.72669845,
        0.86578692, 0.03802867]])

6) Вектор чисел от 1 до 50 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрицы. Найти произведение этих матриц. Найти обратную матрицу этого произведения.  (6 баллов)

In [35]:
arr = np.array(range(51))[1:]
arrOdd = arr[1::2].reshape((5,5))
arrEven = arr[::2].reshape((5,5))
result = np.dot(arrOdd, arrEven)
result, result.T

(array([[ 830,  890,  950, 1010, 1070],
        [1880, 2040, 2200, 2360, 2520],
        [2930, 3190, 3450, 3710, 3970],
        [3980, 4340, 4700, 5060, 5420],
        [5030, 5490, 5950, 6410, 6870]]),
 array([[ 830, 1880, 2930, 3980, 5030],
        [ 890, 2040, 3190, 4340, 5490],
        [ 950, 2200, 3450, 4700, 5950],
        [1010, 2360, 3710, 5060, 6410],
        [1070, 2520, 3970, 5420, 6870]]))

7) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. (5 баллов)

In [14]:
matrix = np.zeros((8,8))
for i in [0,2,-2,4,-4,6,-6]:
    matrix += np.eye(8, k=i);
matrix

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])